version: '3'
services:
  node-train-delay:
    container_name: node-train-delay
    image: ses2/node:8-axios
    environment:
      - LINE_TOKEN=$LINE_TOKEN
    tty: true
    volumes:
      - ./app:/app
    
